// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:29cf80f3-888a-4ab8-bab0-48d5a77cd897',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'lazsocsite-hosting-mobilehub-1285919350',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd2gk3cb1dtc4kl.cloudfront.net',
aws_mobile_analytics_app_id : '5a495e1153e241298b8b0950926dc00d',
aws_project_id : 'c3261b58-5c06-4cc8-94b8-98ea6b8bb46b',
aws_project_name : 'Lazsoc Site',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'lazsocsite-mobilehub-1285919350',
aws_user_files : 'enable',
aws_user_files_s3_bucket : 'lazsocsite-userfiles-mobilehub-1285919350',
aws_user_files_s3_bucket_region : 'us-east-1',
aws_user_settings : 'enable',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});